---
kind: pipeline
name: default

clone:

steps:
  - name: build
    image: node:18-bullseye-slim
    commands:
      - npm install
      - npm run build
      - mv webserver/.htaccess build

  - name: deployment
    image: joomlaprojects/docker-images:packager
    depends_on:
      - build
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_API_TOKEN
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - node_modules/.bin/wrangler pages deploy ./build --project-name manual | tee /tmp/output.log
      - export PREVIEW_URL=`grep Deployment /tmp/output.log | awk '{ print $5 }'`
      - chmod +x test.sh
      - if [ ! -z "$${DRONE_PULL_REQUEST}" ]; then /bin/add_github_status.sh "Preview" "Generated preview for this pull request" "$${PREVIEW_URL}" ; fi;
    when:
      branch:
        main
      status:
        - success
      event:
        - push
        - pull_request

---
kind: signature
hmac: 800855716e91b511049bf0cdd14e76de48d93424321eb77032223f6b48775dc1

...
